### ISSUE TITLE
"resource/empty.png" is missing

### ISSUE THREAD

**Issue by DamirGalas** [rahmatnazali/pimage#3] opened 2019-01-04 09:35 UTC
When I run main_GUI.py I get an error:
```
Traceback (most recent call last):
  File "main_GUI.py", line 123, in <module>
    app = aFrame(root)
  File "main_GUI.py", line 23, in __init__
    self.initUI()
  File "main_GUI.py", line 44, in initUI
    imageLeft = Image.open("resource/empty.png")
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] **No such file or directory: 'resource/empty.png'**

```

**Comment by rnazali** [comment] 2019-03-21 23:32
Duplicate of #1 

You just need to make a, say, 800x800 of black PNG images.
This is really just a cosmetic. Sorry I removed it for the brievity.

**Closed as completed** 2019-03-21 23:37 UTC
